version: '3.5'

services:
  transaction:
    container_name: csf_transaction
    image: csf_transaction-image
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME_ARG: CSF-transaction
        WAR_NAME_ARG: transaction-0.0.1-SNAPSHOT.war
        DATABASE_NAME_ARG: postgres
        MASTER_USERNAME_ARG: csf
        MASTER_PASSWORD_ARG: Y3NmLXRlYW0
        DATABASE_PORT_ARG: 5432
        DATASOURCE_URL_ARG: "jdbc:postgresql://csf_postgres:5432/postgres"
        PROFILES_ACTIVE_ARG: dev
    volumes:
      - .:/var/transaction
      - ./libs:/root/.gradle/
    depends_on:
      - postgres
      - pgadmin
    restart: always
    ports:
      - 8080:8080
    networks: 
      - csf_trans

  postgres:
    container_name: csf_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-csf}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Y3NmLXRlYW0}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - csf_trans
    restart: unless-stopped
  
  pgadmin:
    container_name: csf_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-csf.whoami@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Y3NmLXRlYW0}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - csf_trans
    restart: unless-stopped

networks:
  csf_trans:
    driver: bridge

volumes:
    postgres:
    pgadmin:
